name: Test Schedule Pure

on:
  schedule:
    - cron: '*/1 * * * *'  # Ogni minuto

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "SE VEDI QUESTO, LO SCHEDULE FUNZIONA!"
